GST_Program/Controllers/AdminController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using GST_Program.Domain.Models;
using GST_Program.Domain.Services;
using GST_Program.Models;
using System;
using System.IO;

namespace GST_Program.Controllers {
	public class AdminController : Controller {

		#region People

		// GET: Admin
		public ActionResult Index() {
			return View();
		}

		// GET: Admin/PersonType
		public ActionResult PersonType(string type) {
			var service = new Database();
			var pvm = service.ReadAllPersonByType(type);
			return View("PersonSearch", pvm);
		}

		// GET: Admin/PersonDetail
		public ActionResult PersonDetail(string id) {
			var service = new Database();
			var result = service.ReadSinglePerson(id);
			return View(result);
		}

		// GET: Admin/PersonEdit
		public ActionResult PersonEdit(string id) {
			var service = new Database();
			var result = service.ReadSinglePerson(id);
			return View(result);
		}

		// POST: Admin/PersonEdit
		[HttpPost]
		public ActionResult PersonEdit(Person p) {
			if (ModelState.IsValid) {
				var service = new Database();
				service.Update(p);
				return RedirectToAction("Index");
			}

			return View(p);
		}

		// GET: Admin/PersonDelete
		public ActionResult PersonDelete(string id) {
			var service = new Database();
			var result = service.ReadSinglePerson(id);
			return View(result);
		}

		// POST: Admin/PersonDelete
		[HttpPost]
		public ActionResult PersonDelete(Person p) {
			var service = new Database();
			service.Delete(p);
			return RedirectToAction("Index");
		}

		// GET: Admin/PersonCreate
		public ActionResult PersonCreate() {
			return View();
		}

		// POST: Admin/PersonCreate
		[HttpPost]
		public ActionResult PersonCreate(Person p) {
			var service = new Database();

			if (ModelState.IsValid) {
				service.Create(p);
				return RedirectToAction("Index");
			}

			// Return same Person if invalid field(s)
			return View(p);
		}

		#endregion

		#region BadgeBank

		// GET: Admin/BadgeBank
		public ActionResult BadgeBank() {
			var service = new Database();
			var b = service.ReadAllBadge();
			return View(b);
		}

		// GET: Admin/BadgeBankType
		public ActionResult BadgeBankType(string type) {
			var service = new Database();
			List<Badge> bb;

			if (type == "All")
				bb = service.ReadAllBadge();
			else
				bb = service.ReadAllBadgeByType(type);

			return View("BadgeBankSearch", bb);
		}

		// GET: Admin/BadgeCreate
		public ActionResult BadgeCreate() {
			return View();
		}

		// POST: Admin/BadgeCreate
		[HttpPost]
		public ActionResult BadgeCreate(Badge b) {
			var service = new Database();

			if (ModelState.IsValid) {
				service.Create(b);
				return RedirectToAction("BadgeBank");
			}

			// Return same Badge if invalid field(s)
			return View(b);
		}

		// GET: Admin/BadgeDetail
		public ActionResult BadgeDetail(string id) {
			var service = new Database();
			var b = service.ReadSingleBadge(id);
			return View(b);
		}

		// GET: Admin/BadgeEdit
		[HttpGet]
		public ActionResult BadgeEdit(string id) {
			var service = new Database();
			var b = service.ReadSingleBadge(id);
			return View(b);
		}

		// POST: Admin/BadgeEdit
		[HttpPost]
		public ActionResult BadgeEdit(Badge b) {
			if (ModelState.IsValid) {
				var service = new Database();
				service.Update(b);
				return RedirectToAction("BadgeBank");
			}

			return View(b);
		}

		// GET: /Admin/BadgeDelete
		public ActionResult BadgeDelete(string id) {
			var service = new Database();
			var b = service.ReadSingleBadge(id);
			return View(b);
		}

		// POST: /Admin/BadgeDelete
		[HttpPost]
		public ActionResult BadgeDelete(Badge b) {
			var service = new Database();
			service.Delete(b);
			return RedirectToAction("BadgeBank");
		}

		#endregion

		#region BadgeHistory

		// Okay, so here is the lowdown on the BadgeHistory pages:
		// in a JQuery call, you will direct it to one of these
		// view calls depending on what the Admin is searching for
		// (i.e. if the Admin wants to see who has sent Badge x,
		// or what badges that Giver y has given, or what badges
		// Student z has received).

		// GET: Admin/BadgeHistory
		public ActionResult BadgeHistory() {
			return View();
		}

		// POST: Admin/BadgeHistoryGiver
		[HttpPost]
		public ActionResult BadgeHistoryGiver(string id) {
			var service = new Database();

			if (!TestString.IsAllDigits(id)) {
				Person p = service.ReadSinglePersonByName(id);

				if (p != null)
					id = p.Person_ID;
			}

			List<BadgeHistory> result = service.ReadAllBadgeReceivedByGiver(id);
			return View("BadgeHistorySearch", result);
		}

		// POST: Admin/BadgeHistoryReceiver
		[HttpPost]
		public ActionResult BadgeHistoryReceiver(string id) {
			var service = new Database();

			if (!TestString.IsAllDigits(id)) {
				Person p = service.ReadSinglePersonByName(id);

				if (p != null)
					id = p.Person_ID;
			}

			List<BadgeHistory> result = service.ReadAllBadgeReceivedByReceiver(id);
			return View("BadgeHistorySearch", result);
		}

		// POST: Admin/BadgeHistoryBadge
		[HttpPost]
		public ActionResult BadgeHistoryBadge(string id) {
			var service = new Database();

			if (!TestString.IsAllDigits(id)) {
				Badge b = service.ReadSingleBadgeByName(id);

				if (b != null)
					id = Convert.ToString(b.Badge_ID);
			}

			List<BadgeHistory> result = service.ReadAllBadgeReceivedByBadge(id);
			return View("BadgeHistorySearch", result);
		}

		#endregion

		#region Export

		// GET: ExportPerson
		public void ExportPerson() {
			var fileData = new ExportData().BuildData<Person>();

			Response.Clear();
			Response.ContentType = "text/csv";
			Response.AddHeader("content-disposition", "attachment; filename=person.csv");
			Response.Write(fileData.ToString());
			Response.Flush();
			Response.End();
		}


		// GET: ExportBadge
		public void ExportBadge() {
			var fileData = new ExportData().BuildData<Badge>();

			Response.Clear();
			Response.ContentType = "text/csv";
			Response.AddHeader("content-disposition", "attachment; filename=badgebank.csv");
			Response.Write(fileData.ToString());
			Response.Flush();
			Response.End();
		}


		// GET: ExportBadgeHistory
		public void ExportBadgeHistory() {
			var fileData = new ExportData().BuildData<BadgeHistory>();

			Response.Clear();
			Response.ContentType = "text/csv";
			Response.AddHeader("content-disposition", "attachment; filename=badgehistory.csv");
			Response.Write(fileData.ToString());
			Response.Flush();
			Response.End();
		}

		#endregion
	}
}

GST_Program/Controllers/TreeController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using GST_Program.Domain.Models;
using GST_Program.Domain.Services;
using GST_Program.Models;

namespace GST_Program.Controllers {
	public class TreeController : Controller {

		// GET: Tree
		public ActionResult Index(string id) {
			var service = new Database();
			var person = service.ReadSinglePerson(id);
			ViewBag.Person = person;
			List<BadgeHistory> b = service.ReadAllBadgeReceivedByReceiver(id);
			return View(b);
		}


		// GET: Tree/Grid
		public ActionResult Grid(string id) {
			var service = new Database();
			var person = service.ReadSinglePerson(id);
			ViewBag.Person = person;

			List<Core> core = service.ReadAllCores();
			ViewBag.Core = core;

			var badgeHistoryList = service.ReadAllBadgeReceivedByReceiver(id);

			return View(badgeHistoryList);
		}


		// GET: Tree/BadgeHistoryDetail
		public ActionResult BadgeHistoryDetail(string id) {
			var service = new Database();
			var b = service.ReadSingleBadgeReceived(id);
			return View(b);
		}

		#region Give Badge

		// GET: Tree/GiveBadge
		public ActionResult GiveBadge() {
			var service = new Database();
			var bb = service.ReadAllBadge();
			var pvm = service.ReadAllPerson();

			ViewBag.Badges = bb;
			ViewBag.People = pvm;

			return View();
		}


		// POST: Tree/GiveBadge
		[HttpPost]
		public ActionResult GiveBadge(FormCollection form) {
			var service = new Database();
			BadgeHistory b = new BadgeHistory();
			
			var receiver = form["receiver"];
			var comment = form["Comment"];
			
			// Find Badge
			b.Badge = service.ReadSingleBadge(form["badge"]);
			b.Badge_ID = b.Badge.Badge_ID;
			
			// Find Person logged in
			b.Giver = service.ReadSinglePersonByName(form["giver"]);
			b.Giver_ID = Convert.ToString(b.Giver.Person_ID);

			// Test to see if Form Input for Receiver is a Name or a Number
			if (!TestString.IsAllDigits(receiver)) {
				b.Receiver = service.ReadSinglePersonByName(receiver);
				b.Student_ID = Convert.ToString(b.Receiver.Person_ID);
			}

			b.Time_Stamp = DateTime.Now;
			b.Comment = comment;

			var count = service.ReadAllBadgeReceivedByReceiver(b.Student_ID).Count;

			//replace '1' with the badge count for a person (or any positive number if you want a different position)
			TreeAlgorithm.point bPos = TreeAlgorithm.TreePos(TreeAlgorithm.BinPercent((count + 1)), -32.0f);

			b.Pos_X = bPos.pos_x;
			b.Pos_Y = bPos.pos_y;
			b.Angle = bPos.angle;
			//rotation angle will be put here

			if (ModelState.IsValid) {
				service.Create(b);
               			service.SendEmail(b);
				return RedirectToAction($"Index/{b.Student_ID}");
			}

			return View(b);
		}

		#endregion
	}
}

GST_Program/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - GST</title>
    @Styles.Render("~/bundles/css/bootstrap")
    @Styles.Render("~/bundles/css/datatables")
    @Styles.Render("~/bundles/css/fontawesome")
    @Styles.Render("~/Content/Site.css")

    @RenderSection("additionalCSS", false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div id="navbar" class="navbar-collapse collapse">
                    <a class="navbar-left" id="OCBrand" href="#">
                        <img alt="Brand" src="~/Content/oc logo no black.png" style="height: 44px; width: 40px;" />
                    </a>
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Person", "Index", "Admin")</li>
                        <li>@Html.ActionLink("Badge Bank", "BadgeBank", "Admin")</li>
                        <li>@Html.ActionLink("Badge History", "BadgeHistory", "Admin")</li>
                        <li>@Html.ActionLink("Give Badge", "GiveBadge", "Tree")</li>
                        <li>@Html.ActionLink("Grid View", "Grid/10010", "Tree")</li>
                        <li>@Html.ActionLink("Tree View", "Index/10010", "Tree")</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/js/jquery")
    @Scripts.Render("~/bundles/js/bootstrap")
    @Scripts.Render("~/bundles/js/datatables")

    @RenderSection("scriptsIncludes", false)
    @RenderSection("inlineScript", false)
</body>
</html>

GST_Program/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - GST</title>
    @Styles.Render("~/bundles/css/bootstrap")
    @Styles.Render("~/bundles/css/datatables")
    @Styles.Render("~/bundles/css/fontawesome")
    @Styles.Render("~/Content/Site.css")

    @RenderSection("additionalCSS", false)

    @*<script>
        $(document).ready(function () {
            var admin = sessionStorage
        });
    </script>*@
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div id="navbar" class="navbar-collapse collapse">
                    <a class="navbar-left" id="OCBrand" href="#">
                        <img alt="Brand" src="~/Content/oc logo no black.png" style="height: 44px; width: 40px;" />
                    </a>
                    <ul class="nav navbar-nav">
                        @*<li id="adminLink">@Html.ActionLink("Person", "Index", "Admin")</li>
                        <li id="adminLink">@Html.ActionLink("Badge Bank", "BadgeBank", "Admin")</li>
                        <li id="adminLink">@Html.ActionLink("Badge History", "BadgeHistory", "Admin")</li>
                        <li id="adminLink">@Html.ActionLink("Give Badge", "GiveBadge", "Tree")</li>
                        <li id="adminLink">@Html.ActionLink("Grid View", "Grid/10010", "Tree")</li>*@

                        <li>@Html.ActionLink("Give Badge", "GiveBadge", "Tree")</li>
                        <li>@Html.ActionLink("Grid View", "Grid/10010", "Tree")</li>
                        <li>@Html.ActionLink("Tree View", "Index/10010", "Tree")</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/js/jquery")
    @Scripts.Render("~/bundles/js/bootstrap")
    @Scripts.Render("~/bundles/js/datatables")

    @RenderSection("scriptsIncludes", false)
    @RenderSection("inlineScript", false)
</body>
</html>

GST_Program/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - GST</title>
    @Styles.Render("~/bundles/css/bootstrap")
    @Styles.Render("~/bundles/css/datatables")
    @Styles.Render("~/bundles/css/fontawesome")
    @Styles.Render("~/Content/Site.css")

    @RenderSection("additionalCSS", false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div id="navbar" class="navbar-collapse collapse">
                    <a class="navbar-left" id="OCBrand" href="#">
                        <img alt="Brand" src="~/Content/oc logo no black.png" style="height: 44px; width: 40px;" />
                    </a>
                    <ul class="nav navbar-nav" id="logout">
                        <li >LOG OUT</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/js/jquery")
    @Scripts.Render("~/bundles/js/bootstrap")
    @Scripts.Render("~/bundles/js/datatables")

    @RenderSection("scriptsIncludes", false)
    @RenderSection("inlineScript", false)
</body>
</html>